project_id = "xtzcumhuyxphesbjxjxn"

[functions.create-livestream]
verify_jwt = false

[functions.send-gift]
verify_jwt = true

[functions.get-livestreams]
verify_jwt = false

[functions.claim-tokens]
verify_jwt = false

[functions.get-token-balance]
verify_jwt = false

[functions.update-livestream-status]
verify_jwt = false